decentraland/auth

- src/components/Pages/CallbackPage/CallbackPage.tsx
- src/components/Pages/CallbackPage/index.ts
- src/components/Pages/DefaultPage/DefaultPage.tsx
- src/components/Pages/DefaultPage/index.ts
- src/components/Pages/UserPage/UserPage.tsx
- src/components/Pages/UserPage/index.ts
- src/hooks/redirection.ts
- src/main.tsx
This PR adds the following pages:
- Default: redirect the user to the user page if logged or to the login site otherwise.
- Callback: read the Magic callback login data and redirect the user accordingly.
- User page: renders a blank user page.
> feat: Default, callback, and user pages

- .eslintrc.cjs
- .github/workflows/audit.yml
- .github/workflows/build-release.yaml
- .github/workflows/codeql.yml
- .github/workflows/set-rollout-manual.yaml
- .github/workflows/set-rollout.yaml
- .github/workflows/test.yaml
- .husky/pre-commit
- index.html
- package-lock.json
- package.json
- public/package.json
- scripts/prebuild.cjs
- src/components/Connection/ConnectionIcon/ConnectionIcon.tsx
- src/components/Pages/CallbackPage/CallbackPage.tsx
- src/components/Pages/DefaultPage/DefaultPage.tsx
- src/components/Pages/LoginPage/utils.ts
- src/components/Pages/UserPage/UserPage.tsx
- src/main.tsx
- src/modules/config/env/dev.json
- src/modules/config/env/prod.json
- src/modules/config/env/stg.json
This PR does the following:
- Adds the husky directives to lint and fix code.
- Adds the GH actions to deploy the site.
- Updates `decentraland-connect` and integrates it to support magic.
- Modifies the user page so it does something with the user's connection.
> feat: Add husky and GH actions

- .github/workflows/set-rollout-manual.yaml
- .github/workflows/set-rollout.yaml
set new rollout strategy to deploy by path
> fix: set new rollout actions

- src/main.tsx
Add basename for deploy by paths
> fix: set basename

- vite.config.ts
Use cdn instead of profile as public url for loading assets
> feat: use cdn as public url

- package-lock.json
- package.json
- src/components/ConnectionModal/ConnectionModal.tsx
- src/components/ConnectionModal/ConnectionModal.types.ts
- src/components/ConnectionModal/utils.ts
- src/components/Pages/LoginPage/LoginPage.tsx
- src/components/Pages/LoginPage/utils.ts
Save sign in info using LocalStorageUtils in single sign on library
> feat: save sign in information on local storage

- src/components/Pages/DefaultPage/DefaultPage.tsx
- src/hooks/redirection.ts
- Save query params when redirecting to login
- Allow redirects to same host
> fix: save query params on redirect

- src/components/Pages/LoginPage/utils.ts
- src/main.tsx
- vite.config.ts
Set auth as basename by default
> feat: set basename as auth

- src/components/Pages/CallbackPage/CallbackPage.tsx
- src/components/Pages/LoginPage/LoginPage.tsx
- src/hooks/redirection.ts
Use encoding/decoding for redirectTo search param
> fix: decode uri component redirectTo

- src/components/Pages/LoginPage/LoginPage.module.css
- src/components/Pages/LoginPage/LoginPage.tsx
Add the redirect to explorer with guest option to load without signing in
> feat: add explorer guest option

- index.html
- src/components/Connection/Connection.tsx
- src/components/Connection/Connection.types.ts
- src/components/Connection/ConnectionOption/ConnectionOption.tsx
- src/components/Connection/ConnectionOption/ConnectionOption.types.ts
- src/components/ConnectionModal/ConnectionModal.tsx
- src/components/ConnectionModal/ConnectionModal.types.ts
- src/components/ConnectionModal/utils.ts
- src/components/Pages/CallbackPage/CallbackPage.tsx
- src/components/Pages/LoginPage/LoginPage.module.css
- src/components/Pages/LoginPage/LoginPage.tsx
Add loading states and support for mobile dimensions
> fix: add loading states and mobile support

- src/components/Pages/RequestPage/RequestPage.module.css
- Change the background of the requests page
> fix: Small Changes

- src/components/Connection/Connection.tsx
- src/components/Connection/Connection.types.ts
- src/components/MagicInformationModal/MagicInformationModal.module.css
- src/components/MagicInformationModal/MagicInformationModal.tsx
- src/components/MagicInformationModal/MagicInformationModal.types.ts
- src/components/MagicInformationModal/index.ts
- src/components/Pages/LoginPage/LoginPage.tsx
- src/components/WalletInformationModal/WalletInformationModal.tsx
Add learn more modal for magic
> feat: add learn more magic

- src/components/Pages/RequestPage/RequestPage.module.css
- src/components/Pages/RequestPage/RequestPage.tsx
> fix: Show change account when needed and errors

- src/components/Pages/CallbackPage/CallbackPage.module.css
- src/components/Pages/CallbackPage/CallbackPage.tsx
> remove learn more

- src/components/Pages/CallbackPage/CallbackPage.tsx
- src/components/Pages/RequestPage/RequestPage.tsx
- src/shared/errors.ts
This PR changes the way we're interacting with the scenes, making rejections or denials reach the scenes.
> feat: Send errors to scene

- src/components/Pages/CallbackPage/CallbackPage.tsx
- src/components/Pages/LoginPage/LoginPage.tsx
This PR increases wait to ensure the tracking mechanism works properly.
> fix: Increase wait to ensure tracking

- src/components/FeatureFlagsProvider/FeatureFlagsProvider.tsx
- src/components/FeatureFlagsProvider/FeatureFlagsProvider.types.ts
- src/components/FeatureFlagsProvider/index.ts
- src/components/Pages/RequestPage/RequestPage.tsx
- src/components/Pages/SetupPage/SetupPage.tsx
- src/components/Pages/SetupPage/index.ts
- src/main.tsx
- src/modules/config/env/dev.json
- src/modules/config/env/prod.json
- src/modules/config/env/stg.json
> fix: Feature flags provider + Setup page route

- src/components/Pages/SetupPage/SetupPage.module.css
- src/components/Pages/SetupPage/SetupPage.tsx
> feat: Left part of setup

- src/components/Pages/SetupPage/SetupPage.tsx
- src/modules/analytics/types.ts
> fix: Add tracking events

- src/components/Pages/SetupPage/SetupPage.module.css
- src/components/Pages/SetupPage/SetupPage.tsx
https://github.com/decentraland/auth/assets/24811313/fe192e88-4c76-4bf0-bc06-d99dd81475aa
Add loader to preview.
> fix: Add loader to avatar preview

- src/components/Pages/SetupPage/SetupPage.module.css
- src/components/Pages/SetupPage/SetupPage.tsx
> fix: Mobile support

- src/components/Pages/SetupPage/SetupPage.tsx
> fix: Button message depending on redirect

- .github/workflows/build-release.yaml
- .github/workflows/test.yaml
- README.md
- package.json
This PR updates the build process to use node 20.
> fix: Update to node 20

- src/components/Pages/DefaultPage/DefaultPage.tsx
- src/components/Pages/RequestPage/RequestPage.tsx
- src/components/Pages/SetupPage/SetupPage.tsx
- src/shared/connection.ts
> fix: Correctly redirect user to the request page

- package-lock.json
- package.json
- src/components/ConnectionModal/utils.ts
- src/components/FeatureFlagsProvider/FeatureFlagsProvider.types.ts
- src/components/Pages/CallbackPage/CallbackPage.tsx
- src/components/Pages/LoginPage/LoginPage.tsx
- src/components/Pages/LoginPage/utils.ts
This PR changes the Magic App we're using on the development environment for a testing one, allowing us to test changes in the Magic configuration.
> feat: Use magic test app on dev

- src/components/Intercom/Intercom.tsx
- src/components/Intercom/Intercom.types.ts
- src/components/Intercom/IntercomWidget.ts
- src/components/Intercom/index.ts
- src/main.tsx
- src/modules/config/env/dev.json
- src/modules/config/env/prod.json
- src/modules/config/env/stg.json
This PR adds the `Intercom` component and widget from `decentraland-dapps`.
> feat: Add intercom

- package.json
- src/components/FeatureFlagsProvider/FeatureFlagsProvider.types.ts
- src/components/Pages/CallbackPage/CallbackPage.tsx
This PR removes the confirm log in process when the magic auto sign in feature flag is set.
> feat: Remove confirm log in

- src/components/Connection/Connection.module.css
- src/components/Connection/Connection.tsx
by https://docs.google.com/presentation/d/1XVP5rNh4QHnL5wF3xYiKGGSsgq_Ri58dHJiJ86RZsc0/edit#slide=id.g32dbe94bcf5_4_6
> feat: update copy

- package-lock.json
- package.json
This PR updates the auth build dependencies to their latest versions.
> fix: Update build dependencies

- src/components/Pages/RequestPage/RequestPage.tsx
- src/hooks/targetConfig.ts
This PR changes the copy in the `RequestPage` to a new one.
> fix: Verify number copy

- src/components/Pages/LoginPage/LoginPage.tsx
- src/components/Pages/SetupPage/SetupPage.tsx
- src/modules/analytics/types.ts
This PR adds three new events requested by the data team to the site.
> feat: Enhance auth logging

- src/components/Pages/RequestPage/RequestPage.tsx
- src/shared/auth/httpClient.spec.ts
- src/shared/auth/httpClient.ts
- src/shared/auth/types.ts
- src/shared/auth/wsClient.spec.ts
- src/shared/auth/wsClient.ts
This PR adds the capability to request the explorer to notify that a request requires code validation.
> feat: Add validation notification request

- src/components/Pages/RequestPage/RequestPage.tsx
This PR adds logging to the sign in process to understand what's going on during debug sessions.
> fix: Add logging to sign in process

- src/components/Pages/RequestPage/RequestPage.tsx
- src/hooks/useAuthFlow.ts
In this PR we’re introducing a flag so that if the system is iOS, it skips the new onboarding.
> feat: add ios flag

- src/components/CustomWearablePreview/CustomWearablePreview.tsx
- src/components/Pages/LoginPage/LoginPage.tsx
- src/components/Pages/RequestPage/RequestPage.tsx
- src/hooks/useAuthFlow.ts
- src/shared/utils/webgpu.ts
Add fallback to old onboarding when WebGPU is not supported
> fix: check webgpu for old onboarding
